FROM alpine:3.11.5
MAINTAINER Gaby Fulchic <gaby.fulchic@ynov.com>
LABEL container_type=flaskapp

RUN echo -e "http://nl.alpinelinux.org/alpine/v3.5/main\nhttp://nl.alpinelinux.org/alpine/v3.5/community" > /etc/apk/repositories
RUN apk update && apk upgrade && apk add --no-cache python2 py-pip
RUN chmod 0755 /usr/bin && mkdir -p /var/www/app && chmod -R 0755 /var/www/app

WORKDIR /var/www/app

RUN pip install --upgrade pip && pip install -U Flask

CMD ["python2","/var/www/app/main.py"]
